var tableauQuestion = [
         {   question : "¿Cuál es el mejor remedio para combatir el sueño?",
        propositionA : "Tomar algún estimulante.",
        propositionB : "Dormir",
        propositionC : "Ventilar bien el vehículo.",
        propositionD : "Seguir conduciendo.",
        reponse : "B"},
		
         {   question : "¿Hay que prestar una atención especial a los peatones?",
        propositionA : "No, porque no representan ningún peligro.",
        propositionB : "Sólo en vías urbanas.",
        propositionC : "Sí, porque son especialmente vulnerables a los peligros del tráfico.",
        propositionD : "",
        reponse : "C"},
		
        {   question : "Entre la dotación obligatoria que debe llevar un turismo, ¿se encuentra un extintor?",
        propositionA : "No.",
        propositionB : "Sí.",
        propositionC : "Sí, pero solamente cuando circule por vías fuera de poblado.",
        propositionD : "",
        reponse : "A"},
	
	{   question : "Los accidentes debidos a distracciones suceden más...",
        propositionA : "durante la tarde.",
        propositionB : "en los meses de invierno.",
        propositionC : "durante el día y los fines de semana.",
        propositionD : "Todas las anteriores",
        reponse : "C"},
		
	{   question : "¿Qué nivel de alcohol en la sangre se clasifica como conducir en estado de ebriedad?",
        propositionA : "0.50",
        propositionB : "0.15",
        propositionC : "0.00",
        propositionD : "0.25",
        reponse : "C"},
		
	{   question : "Cuando la calzada está helada...",
        propositionA : "la distancia de frenado se mantiene igual que en condiciones normales.",
        propositionB : "la distancia de frenado aumenta.",
        propositionC : "la distancia de frenado disminuye.",
        propositionD : "Nadita",
        reponse : "B"},
	
	{   question : "Los agentes de la Autoridad de Tráfico, ¿cuándo podrán proceder a la inmovilización de una motocicleta?",
        propositionA : "Cuando su conductor no lleve puesto el casco.",
        propositionB : "Cuando el pasajero de la misma circule sin el casco.",
        propositionC : "En ningún caso.",
        propositionD : "Nunca",
        reponse : "A"},
		
	{   question : "¿Cuál es la velocidad máxima fuera de poblado en autovía / autopísta",
        propositionA : "300 km/h",
        propositionB : "200 km/h",
        propositionC : "120 km/h",
        propositionD : "90 km/h",
        reponse : "C"},
		
	{   question : "¿Qué debe hacer ante las indicaciones de los agentes?",
        propositionA : "Pasar por el lado izquierdo porque el agente va a parar a la derecha.",
        propositionB : "Detenerse en el lado derecho.",
        propositionC : "Reducir la marcha.",
        propositionD : "",
        reponse : "B"},
		
	{   question : "En los turismos, el espejo retrovisor izquierdo es...",
        propositionA : "obligatorio sólo cuando el retrovisor interior no permite el campo de visión reglamentario.",
        propositionB : "siempre obligatorio.",
        propositionC : "opcional",
        propositionD : "Todas las anteriores",
        reponse : "B"},

        {   question : "Los niños suelen tener problemas en el tráfico porque...",
        propositionA : "su campo visual es mayor.",
        propositionB : "su visión periférica es mayor.",
        propositionC : "no conocen todos los comportamientos adecuados para circular.",
        propositionD : "",
        reponse : "C"},

        {   question : "Si conduce una motocicleta, ¿es aconsejable utilizar guantes?",
        propositionA : "Sí, incluso en verano, para proteger las manos en caso de caída.",
        propositionB : "No, porque pueden dificultar la conducción.",
        propositionC : "Sí, su uso es obligatorio en todo tipo de vías.",
        propositionD : "",
        reponse : "A"},

        {   question : "¿Dónde sufren los peatones más accidentes?",
        propositionA : "En las ciudades.",
        propositionB : "En las vías interurbanas.",
        propositionC : "Tanto en poblado como fuera de poblado la cantidad de accidentes es igual.",
        propositionD : "",
        reponse : "A"},

        {   question : "Las normas del cinturón de seguridad, ¿a qué obligan?",
        propositionA : "A llevarlo puesto y abrochado siempre.",
        propositionB : "A llevarlo en el vehículo y abrochármelo sólo en carretera.",
        propositionC : "A llevarlo puesto sin abrochar.",
        propositionD : "",
        reponse : "A"},

        {   question : "¿Qué es el ángulo muerto?",
        propositionA : "Es una zona alrededor del vehículo que no se ve con los retrovisores.",
        propositionB : "Es una parte de los coches que puede producir accidentes.",
        propositionC : "Es la zona sin visibilidad que tiene el conductor al tomar una curva.",
        propositionD : "",
        reponse : "A"},

        {   question : "No está permitido utilizar la luz de largo alcance cuando...",
        propositionA : "está encendida la luz de corto alcance ",
        propositionB : "pueda deslumbrar a otros usuarios.",
        propositionC : "está encendida la luz de posición.",
        propositionD : "",
        reponse : "B"},

        {   question : "¿Cuándo se producen más accidentes de ciclistas, en verano o en invierno?",
        propositionA : "Es indiferente.",
        propositionB : "En invierno, debido a las condiciones meteorológicas adversas.",
        propositionC : "En verano, puesto que con la llegada del buen tiempo hay más ciclistas en las carreteras.",
        propositionD : "",
        reponse : "C"},

        {   question : "Si circulando le sorprende el sueño debe:",
        propositionA : "Aumentar la velocidad para tratar de llegar cuanto antes a su destino.",
        propositionB : "Estacionar el vehículo en lugar permitido y dormir.",
        propositionC : "Reducir la velocidad y circular por el arcén.",
        propositionD : "",
        reponse : "B"},
]
