ui_page "html/ui.html"

files {
    'html/fonts/gta-ui.ttf',
    "html/ui.html",
    "html/ui.css",
	"html/materialize.css",
    "html/ui.js",
    "html/images/barman.png",
    "html/images/barra_coins.png",
    "html/images/barra_dinero.png",
    "html/images/barra_empleo.png",
    "html/images/barra_energia_llena.png",
    "html/images/barra_energia_vacia.png",
    "html/images/barra_hambre_llena.png",
    "html/images/barra_hambre_vacia.png",
    "html/images/barra_sed_llena.png",
    "html/images/barra_sed_vacia.png",
    "html/images/barra_vida_llena.png",
    "html/images/barra_vida_vacia.png",
    "html/images/dependiente.png",
    "html/images/doctor.png",
    "html/images/emociones_1.png",
    "html/images/emociones_2.png",
    "html/images/mecanico.png",
    "html/images/mochila_1.png",
    "html/images/mochila_2.png",
    "html/images/policia.png",
    "html/images/social_1.png",
    "html/images/social_2.png",
    "html/images/Taskbar_vacia.png",
    "html/images/taxista.png",
    "html/images/telefono_1.png",
    "html/images/telefono_2.png",
    "html/images/vendedor_coches.png",
}

client_script {
    'client/client.lua',
    'config.lua',
}