--Lynx Entities is the most important table, configure it very well

--REMEMBER! If you're going to use Whitelisted Entities in `config.lua` everything here will be converted in Whitelisted Entities...
-- You can choose between Blacklisted or Whitelisted Entities in `config.lua`


LynxEntities = {}

LynxEntities.Objects = {
    [GetHashKey("prop_fnclink_05crnr1")] = true,
    [GetHashKey("xs_prop_hamburgher_wl")] = true,
    [GetHashKey("xs_prop_plastic_bottle_wl")] = true,
    [GetHashKey("prop_windmill_01")] = true,
    [GetHashKey("p_spinning_anus_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
    [GetHashKey("stt_prop_ramp_adj_hloop")] = true,
    [GetHashKey("stt_prop_ramp_adj_loop")] = true,
    [GetHashKey("stt_prop_ramp_jump_l")] = true,
    [GetHashKey("stt_prop_ramp_jump_m")] = true,
    [GetHashKey("stt_prop_ramp_jump_s")] = true,
    [GetHashKey("stt_prop_ramp_jump_xl")] = true,
    [GetHashKey("stt_prop_ramp_jump_xs")] = true,
    [GetHashKey("stt_prop_ramp_jump_xxl")] = true,
    [GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
    [GetHashKey("stt_prop_ramp_spiral_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
    [GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
    [GetHashKey("stt_prop_stunt_track_start")] = true,
    [GetHashKey("stt_prop_stunt_track_hill2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_01")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_02")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_03")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_04")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_05")] = true,
    [GetHashKey("stt_prop_stunt_bblock_hump_01")] = true,
    [GetHashKey("stt_prop_stunt_bblock_hump_02")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg1")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg3")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm1")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm3")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp3")] = true,
    [GetHashKey("prop_beach_fire")] = true,
    [GetHashKey("prop_gas_pump_1a")] = true,
    [GetHashKey("prop_gas_pump_1b")] = true,
    [GetHashKey("prop_gas_pump_1c")] = true,
    [GetHashKey("prop_gas_pump_1d")] = true,
    [GetHashKey("prop_gas_pump_old2")] = true,
    [GetHashKey("prop_gas_pump_old3")] = true,
    [GetHashKey("prop_vintage_pump")] = true,
    [GetHashKey("apa_mp_h_acc_box_trinket_01")] = true,
    [GetHashKey("prop_roundbailer02")] = true,
    [GetHashKey("prop_roundbailer01")] = true,
    [GetHashKey("prop_container_05a")] = true,
    [GetHashKey("stt_prop_stunt_bowling_ball")] = true,
    [GetHashKey("apa_mp_h_acc_rugwoolm_03")] = true,
    [GetHashKey("prop_container_ld2")] = true,
    [GetHashKey("p_ld_stinger_s")] = true,
    [GetHashKey("hei_prop_carrier_cargo_02a")] = true,
    [GetHashKey("p_cablecar_s")] = true,
    [GetHashKey("p_ferris_car_01")] = true,
    [GetHashKey("prop_cj_big_boat")] = true,
    [GetHashKey("prop_rock_4_big2")] = true,
    [GetHashKey("prop_steps_big_01")] = true,
    [GetHashKey("v_ilev_lest_bigscreen")] = true,
    [GetHashKey("prop_carcreeper")] = true,
    [GetHashKey("apa_mp_h_bed_double_09")] = true,
    [GetHashKey("apa_mp_h_bed_wide_05")] = true,
    [GetHashKey("prop_cattlecrush")] = true,
    [GetHashKey("prop_cs_documents_01")] = true,
    [GetHashKey("prop_ferris_car_01_lod1")] = true,
    [GetHashKey("prop_construcionlamp_01")] = true,
    [GetHashKey("prop_fncconstruc_01d")] = true,
    [GetHashKey("prop_fncconstruc_02a")] = true,
    [GetHashKey("p_dock_crane_cabl_s")] = true,
    [GetHashKey("prop_dock_crane_01")] = true,
    [GetHashKey("prop_dock_crane_02_cab")] = true,
    [GetHashKey("prop_dock_float_1")] = true,
    [GetHashKey("prop_dock_crane_lift")] = true,
    [GetHashKey("apa_mp_h_bed_double_08")] = true,
    [GetHashKey("csx_seabed_bldr4_")] = true,
    [GetHashKey("imp_prop_impexp_sofabed_01a")] = true,
    [GetHashKey("apa_mp_h_yacht_bed_01")] = true,
    [-685641702] = true, -- unknown
    [-1230672010] = true, -- unknown
    [-1404869155] = true, -- FBI Buildings
    [-759902142] = true, --Fire
}

LynxEntities.Vehicles = {
    [GetHashKey("cargoplane")] = {name = "Cargo Plane"},
    [GetHashKey("dump")] = {name = "Dump"},
    [GetHashKey("avenger")] = {name = "Avenger"},
    [GetHashKey("avenger2")] = {name = "Avenger2"},
    [GetHashKey("luxor")] = {name = "Luxor"},
    [GetHashKey("khanjali")] = {name = "Khanjali"},
    [GetHashKey("rhino")] = {name = "Rhino"},
    [GetHashKey("insurgent")] = {name = "Insurgent"},
    [GetHashKey("insurgent3")] = {name = "Insurgent3"},
    [GetHashKey("oppressor")] = {name = "Oprresor"},
    [GetHashKey("oppressor2")] = {name = "Oprresor2"},
    [GetHashKey("maverick")] = {name = "Maverick"},
    [GetHashKey("blimp2")] = {name = "blimp2"},
    [GetHashKey("blimp")] = {name = "blimp"},
    [GetHashKey("blimp3")] = {name = "blimp3"},
    [GetHashKey("freight")] = {name = "Freight"},
    [GetHashKey("freightcar")] = {name = "FreightCar"},
    [GetHashKey("limo2")] = {name = "Limo2"},
    [GetHashKey("freightcont1")] = {name = "FreightCont1"},
    [GetHashKey("freightcont2")] = {name = "FreightCont2"},
    [GetHashKey("freightgrain")] = {name = "FreightGrain"},
    [GetHashKey("cerberus3")] = {name = "Cerberus3"},
    [GetHashKey("cerberus2")] = {name = "Cerberus2"},
    [GetHashKey("cerberus")] = {name = "Cerberus"},
    [GetHashKey("buzzard")] = {name = "Buzzard"},
    [GetHashKey("phantom2")] = {name = "Phantom2"},
    [GetHashKey("issi6")] = {name = "Issi6"},
    [GetHashKey("issi4")] = {name = "Issi4"},
    [GetHashKey("issi5")] = {name = "Issi5"},
    [GetHashKey("savage")] = {name = "Savage"},
    [GetHashKey("hunter")] = {name = "Hunter"},
    [GetHashKey("akula")] = {name = "Akula"},
    [GetHashKey("annihilator")] = {name = "Annihilator"},
    [GetHashKey("cutter")] = {name = "Cutter"},
    [GetHashKey("bulldozer")] = {name = "Bulldozer"},
    [GetHashKey("barracks")] = {name = "Barracks"},
    [GetHashKey("barracks2")] = {name = "Barracks2"},
    [GetHashKey("barracks3")] = {name = "Barracks3"},
    [GetHashKey("barrage")] = {name = "Barrage"},
    [GetHashKey("chernobog")] = {name = "Chernobog"},
    [GetHashKey("crusader")] = {name = "Crusader"},
    [GetHashKey("halftrack")] = {name = "HalfTrack"},
    [GetHashKey("minitank")] = {name = "MiniTank"},
    [GetHashKey("scarab")] = {name = "Scarab"},
    [GetHashKey("scarab2")] = {name = "Scarab2"},
    [GetHashKey("scarab3")] = {name = "Scarab3"},
    [GetHashKey("thruster")] = {name = "Thruster"},
    [GetHashKey("trailersmall2")] = {name = "Trailersmall2"},
    [GetHashKey("brutus3")] = {name = "Brutus3"},
    [GetHashKey("freecrawler")] = {name = "Freecrawler"},
    [GetHashKey("monster")] = {name = "Monster"},
    [GetHashKey("monster3")] = {name = "Monster3"},
    [GetHashKey("monster4")] = {name = "Monster4"},
    [GetHashKey("monster5")] = {name = "Monster5"},
    [GetHashKey("technical")] = {name = "Technical"},
    [GetHashKey("technical3")] = {name = "Technical3"},
    [GetHashKey("technical2")] = {name = "Technical2"},
    [GetHashKey("nightshark")] = {name = "Nightshark"},
    [GetHashKey("zhaba")] = {name = "Zhaba"},
    [GetHashKey("formula")] = {name = "Formula"},
    [GetHashKey("formula2")] = {name = "Formula2"},
    [GetHashKey("scramjet")] = {name = "Scramjet"},
    [GetHashKey("zr380")] = {name = "Zr380"},
    [GetHashKey("zr3802")] = {name = "Zr3802"},
    [GetHashKey("zr3803")] = {name = "Zr3803"},
    [GetHashKey("raptor")] = {name = "Raptor"},
    [GetHashKey("volatol")] = {name = "Volatol"},
    [GetHashKey("voltic2")] = {name = "Voltic2"},
    [GetHashKey("tula")] = {name = "Tula"},
    [GetHashKey("strikeforce")] = {name = "Strikeforce"},
    [GetHashKey("lazer")] = {name = "Lazer"},
    [GetHashKey("valkyrie2")] = {name = "Valkyrie2"},
    [GetHashKey("valkyrie")] = {name = "Valkyrie"},
    [GetHashKey("jet")] = {name = "Jet"},
    [GetHashKey("hydra")] = {name = "Hydra"},
    [GetHashKey("bombushka")] = {name = "Bombushka"},
    [GetHashKey("bruiser3")] = {name = "Bruiser3"},
    [GetHashKey("bruiser2")] = {name = "Bruiser2"},
    [GetHashKey("bruiser")] = {name = "Bruiser"},
    [GetHashKey("caracara")] = {name = "Caracara"},
    [GetHashKey("dune5")] = {name = "Dune5"},
    [GetHashKey("dune4")] = {name = "Dune4"},
    [GetHashKey("dune3")] = {name = "Dune3"},
    [GetHashKey("dune2")] = {name = "Dune2"},
    [GetHashKey("dune")] = {name = "Dune"},
    [GetHashKey("openwheel1")] = {name = "Openwheel1"},
    [GetHashKey("paragon2")] = {name = "Paragon2"},
    [GetHashKey("formula")] = {name = "Formula"},
    [GetHashKey("formula2")] = {name = "Formula2"},
    [GetHashKey("blazer5")] = {name = "Blazer5"},
    [GetHashKey("slamvan4")] = {name = "Slamvan4"},
    [GetHashKey("slamvan5")] = {name = "Slamvan5"},
    [GetHashKey("slamvan6")] = {name = "Slamvan6"},
    [GetHashKey("ruiner2")] = {name = "Ruiner2"},
    [GetHashKey("dukes2")] = {name = "Dukes2"},
    [GetHashKey("dominator4")] = {name = "Dominator4"},
    [GetHashKey("dominator5")] = {name = "Dominator5"},
    [GetHashKey("dominator6")] = {name = "Dominator6"},
    [GetHashKey("handler")] = {name = "Handler"},
    [GetHashKey("vindicator")] = {name = "Vindicator"},
    [GetHashKey("wastelander")] = {name = "Wastelander"},
    [GetHashKey("ardent")] = {name = "Ardent"},
    [GetHashKey("vigilante")] = {name = "Vigilante"},
    [GetHashKey("cargobob")] = {name = "Cargobob"},
}

LynxEntities.Peds = {
    [GetHashKey("a_m_y_mexthug_01")] = {name = "MexThug"},
    [GetHashKey("a_c_husky")] = {name = "Huskey"}, 
    [GetHashKey("a_c_boar")] = {name = "Boar"}, 
    [GetHashKey("a_c_sharkhammer")] = {name = "Sharkhammer"}, 
    [GetHashKey("a_c_chimp")] = {name = "Chimp"}, 
    [GetHashKey("a_c_chop")] = {name = "Chop"}, 
    [GetHashKey("a_c_hen")] = {name = "Hen"}, 
    [GetHashKey("a_c_humpback")] = {name = "Humpback"}, 
    [GetHashKey("a_c_killerwhale")] = {name = "Killerwhale"},
    [GetHashKey("a_c_rhesus")] = {name = "Rhesus"}, 
    [GetHashKey("a_c_rottweiler")] = {name = "Rottweiler"}, 
    [GetHashKey("a_c_sharktiger")] = {name = "SharkTiger"}, 
    [GetHashKey("a_c_shepherd")] = {name = "Shepherd"}, 
    [GetHashKey("u_m_y_zombie_01")] = {name = "Zombie"},
    [GetHashKey("a_m_m_acult_01")] = {name = "Acult01"},
    [GetHashKey("u_m_y_juggernaut_01")] = {name = "Juggernaut"},
}