var tableauQuestion = [
    {   question : "Si conduce a 80 kmh y se acerca a una zona residencial, significa que...",
        propositionA : "Necesitarás acelerar más adelante",
        propositionB : "Puedes acelerar mientras no haya otros vehiculos",
        propositionC : "Tendrás que reducir la velocidad por delante",
        propositionD : "Puedes mantener tu velocidad",
        reponse : "C"},
		
    {   question : "Mientras gira a la izquierda en una luz verde, ve que hay un peatón en el cruce de peatones. ¿Quién tiene el derecho de paso?",
        propositionA : "Los peatones, porque pueden cruzar la calle con cualquier luz",
        propositionB : "Tu vehículo porque la luz es verde",
        propositionC : "El peatón, porque está cruzando con la luz verde.",
        propositionD : "Su vehículo, porque los vehículos siempre tienen derecho de paso",
        reponse : "C"},
		
    {   question : "A menos que se publique, la velocidad máxima en un área residencial es de ____ kmh.",
        propositionA : "80",
        propositionB : "120",
        propositionC : "30",
        propositionD : "45",
        reponse : "A"},
	
	{   question : "Antes de cada cambio de carril, deberías.",
        propositionA : "Revisa tus espejos",
        propositionB : "Revisa tus puntos ciegos",
        propositionC : "Señalar sus intencines",
        propositionD : "Todas las anteriores",
        reponse : "D"},
		
	{   question : "¿Qué nivel de alcohol en la sangre se clasifica como conducir en estado de ebriedad?",
        propositionA : "0.50",
        propositionB : "0.15",
        propositionC : "0.00",
        propositionD : "0.25",
        reponse : "C"},
		
	{   question : "Debe detenerse hasta que pase cualquier vehículo de emergencia con sirena, a menos que:",
        propositionA : "Tienes prisa",
        propositionB : "Hay suficiente espacio para ellos en otro carril.",
        propositionC : "Estás en una zona escolar",
        propositionD : "Estas en una interseccion",
        reponse : "D"},
	
	{   question : "El derecho de paso debe ser cedido a los vehículos de emergencia.",
        propositionA : "En todo momento",
        propositionB : "Con luces rojas, azules o blancas intermitentes.",
        propositionC : "Usando una sirena o luces rojas, azules o blancas intermitentes",
        propositionD : "Usando una sirena",
        reponse : "C"},
		
	{   question : "¿Cuál es la velocidad máxima fuera de poblado en autovía / autopísta",
        propositionA : "300 km/h",
        propositionB : "200 km/h",
        propositionC : "120 km/h",
        propositionD : "90 km/h",
        reponse : "C"},
		
	{   question : "¿Cual es el nivel de alcohol seguro para conducir?",
        propositionA : "0.50",
        propositionB : "0.15",
        propositionC : "0.100",
        propositionD : "0.00",
        reponse : "D"},
		
	{   question : "¿Puede realizar un cambio de sentido en un lugar donde esté prohibido adelantar?",
        propositionA : "Si, excepto entre la puesta y la salida de sol, porque disminuye la visibilidad",
        propositionB : "No, salvo que el cambio de sentido esté expresamente autorizado",
        propositionC : "Si, cuando la circulación en sento contrario lo permita",
        propositionD : "Todas las anteriores",
        reponse : "B"},

        {   question : "La mayor parte de las víctimas mortales por accidente de circulación se producen en...",
        propositionA : "vías interurbanas",
        propositionB : "vías urbanas",
        propositionC : "travesías",
        propositionD : "todas las anteriores",
        reponse : "A"},

        {   question : "El conductor debe...",
        propositionA : "observar únicamente a los conductores que se aproximan por detrás",
        propositionB : "mirar siempre hacia adelante",
        propositionC : "observar constantemente lo que sucede en la vía",
        propositionD : "Ninguna de las anteriores",
        reponse : "C"},

        {   question : "Para entrar en una autopista, ¿a qué velocidad debe circular?",
        propositionA : "A la máxima velocidad permitida en la autopista.",
        propositionB : "Siempre muy despacio para entrar con seguridad.",
        propositionC : "A la velocidad adecuada que permita incorporarse con seguridad.",
        propositionD : "Siempre a la máxima velocidad del vehiculo.",
        reponse : "C"},
]
